# Generated by Django 2.0.4 on 2018-04-17 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulos', '0003_auto_20180417_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='modulo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
