# Generated by Django 2.0.4 on 2018-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='modulo',
            name='perfil',
            field=models.ManyToManyField(to='modulos.Perfil'),
        ),
    ]
